version: 0.2

env:
    variables:
        AWS_REGION_NAME: us-west-2
        ECR_REPOSITORY_NAME: sbcntr-backend-koyama
        DOCKER_BUILDKIT: "1"

phases:
    install:
        runtime-versions:
            docker: 20

    pre_build:
        commands:
            - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
            - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION_NAME}.amazonaws.com/${ECR_REPOSITORY_NAME}
            - aws ecr get-login-password --region ${AWS_REGION_NAME} | docker login --username AWS --password-stdin https://${REPOSITORY_URI}
            # タグ名にGitのコミットハッシュを利用
            - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)
    build:
        commands:
            - docker image build -t ${REPOSITORY_URI}:${IMAGE_TAG} .
    post_build:
        commands:
            - docker image push ${REPOSITORY_URI}:${IMAGE_TAG}
            - printf '{"name":"%s","ImageURI":"%s"}' $ECR_REPOSITORY_NAME $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

artifacts:
    files:
        - imageDetail.json
